completed NSP for matomo web - db
BCDevOps/matomo-openshift pull request #16
Opened 2020-12-29 20:53 UTC by wadeking98

2021-01-04 19:36 UTC, esune requested changes
@WadeKing is this deployed somewhere that can be tested? Were you able to step through the initial steps required for matomo to start-up (configuring connection to db and users)?

2021-01-04 19:36 UTC, esune commented on openshift/templates/matomo/matomo-deploy.json
> +        "description": "Allow the controller to talk to either the database or agent micro services.\n",
The description is not accurate, it needs updating.

2021-01-04 19:36 UTC, esune commented on openshift/templates/matomo-db/matomo-db-deploy.json
> +      "value": "4a9599"
Please leave the namespace empty: this will prevent unwanted side-effects when deploying, as the user will have to explicitly specify one when running `./manage -n something init`.

Applies to other configuration files as well.

2021-01-04 19:36 UTC, esune commented on openshift/templates/matomo/matomo-deploy.json
> +      "value": "controller"
This needs to be updated: a netter value is probably just `matomo` in this case.

2021-01-04 19:43 UTC, wadeking98 commented on openshift/templates/matomo/matomo-deploy.json
> +      "value": "controller"
I'll make those changes. Yes I tested it and was able to connect and setup the databse on openshift. It's not on openshift right now, I deleted it to clean up my workspace

2021-01-05 17:35 UTC, esune approved these changes

2021-01-05 17:37 UTC, merged