update to use artifactory
BCDevOps/matomo-openshift pull request #19
Opened 2021-01-06 21:47 UTC by wadeking98

@esune we may need to update the documentation to explian how to configure artifactory with matomo

2021-01-07 00:38 UTC, esune reviewed
@WadeBarnes I think we are okay leaving this as artifactory-only configuration since it is meant to run in openshift anyway (and I am not really sure there is a sane way to have the artifactory config be optional). Just wanted to see if you agree or have adifferent opinion.

2021-01-07 00:38 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +            ]
Is this change a leftover from troubleshooting?

2021-01-07 00:47 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +      "description": "the artifactory pull cred",
Nit.: let's make this even more obvious and use something like `The name of the secret contaning the Artifactory pull credentials`

2021-01-07 00:54 UTC, wadeking98 commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +            ]
No it's not, the guide for setting up artifactory told me to put it in there

2021-01-07 01:00 UTC, wadeking98 commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +      "description": "the artifactory pull cred",
changed description, this is now resolved. Note: because of the genDepls.sh filter, make sure whenever you use the word secret it's lower case or else it will think it's a Secret object.

2021-01-07 01:04 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +            ]
Interesting, I wonder what is it required for - I will ask as I am curious!

2021-01-07 01:05 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +      "description": "the artifactory pull cred",
Oh, lol. I forgot about that, will have to see if we can make the scripts better, but for now we will just have to remember I guess ;)

2021-01-07 01:06 UTC, esune commented
A thing I realized while going through the changes to Fathom is that we probably don't really need/want the `SUFFX` parameter in this project: the reason we add that to other configurations is because the components are reusable and multiple deployments will likely need to coexist in the same namespace. In the case of `matomo` we will likely only have one instance running at any time, so I think we should clean up builds and deployments from `SUFFIX` as it is not really necessary.

2021-01-07 01:20 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +            ]
I actually think they can be removed:
- `BUILD_LOGLEVEL` increases verbosity of the OpenShift build (see [here](https://docs.openshift.com/container-platform/4.3/builds/basic-build-operations.html#builds-basic-access-build-verbosity_basic-build-operations)).
- `NPM_CONFIG_LOGLEVEL` is a NodeJs evironment variable  that also tweaks log verbosity.
Neither one is actually required for the build, so they should go.

2021-01-07 15:48 UTC, WadeBarnes commented
> @WadeBarnes I think we are okay leaving this as artifactory-only configuration since it is meant to run in openshift anyway (and I am not really sure there is a sane way to have the artifactory config be optional). Just wanted to see if you agree or have adifferent opinion.

I'd change the parameter name for the pull secret to something more generic; it's not artifactory specific and we should not imply it is with the name of the parameter.

The build does not have to be artifactory specific.  You can override the `FROM` directive in the Docker file by adding a `dockerStrategy` section to the build like this (from [bcgov/orgbook-configurations - backup-build.json](https://github.com/bcgov/orgbook-configurations/blob/master/openshift/templates/backup/backup-build.json#L52)):
```
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
      dockerfilePath: Dockerfile
```
That way you can leave the `FROM nginx:stable` in the proxy's Dockerfile and inject the artifactory specific URI in the OCP build.  Then we're not forcing our specific infrastructure configuration on others.

2021-01-07 15:49 UTC, WadeBarnes requested changes
See comments

2021-01-07 15:55 UTC, WadeBarnes commented
> A thing I realized while going through the changes to Fathom is that we probably don't really need/want the `SUFFX` parameter in this project: the reason we add that to other configurations is because the components are reusable and multiple deployments will likely need to coexist in the same namespace. In the case of `matomo` we will likely only have one instance running at any time, so I think we should clean up builds and deployments from `SUFFIX` as it is not really necessary.

I'd leave the `SUFFIX` parameter and just default it to being blank.  Someone may want to deploy more than one instance of matomo into a given namespace for some reason, and having the `SUFFIX` parameter makes that super easy.

2021-01-07 16:49 UTC, wadeking98 commented
> > @WadeBarnes I think we are okay leaving this as artifactory-only configuration since it is meant to run in openshift anyway (and I am not really sure there is a sane way to have the artifactory config be optional). Just wanted to see if you agree or have adifferent opinion.
> 
> I'd change the parameter name for the pull secret to something more generic; it's not artifactory specific and we should not imply it is with the name of the parameter.
> 
> The build does not have to be artifactory specific. You can override the `FROM` directive in the Docker file by adding a `dockerStrategy` section to the build like this (from [bcgov/orgbook-configurations - backup-build.json](https://github.com/bcgov/orgbook-configurations/blob/master/openshift/templates/backup/backup-build.json#L52)):
> 
> ```
>   strategy:
>     type: Docker
>     dockerStrategy:
>       from:
>         kind: DockerImage
>         name: 'registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
>       dockerfilePath: Dockerfile
> ```
> 
> That way you can leave the `FROM nginx:stable` in the proxy's Dockerfile and inject the artifactory specific URI in the OCP build. Then we're not forcing our specific infrastructure configuration on others.

how do we inject the artifactory creds with this new configuration?

2021-01-07 17:17 UTC, WadeBarnes commented
The same way you are now with the `pullSecret`, you just need to add the `from` section to the equation.

2021-01-07 17:18 UTC, WadeBarnes commented
I'm also recommending changing the name of the `ARTIFACTORY_CREDS` parameter to something more generic.  `pullSecrets` are not antifactory specific and we don't want to imply they are.

2021-01-07 17:20 UTC, esune commented
> 
> 
> > > @WadeBarnes I think we are okay leaving this as artifactory-only configuration since it is meant to run in openshift anyway (and I am not really sure there is a sane way to have the artifactory config be optional). Just wanted to see if you agree or have adifferent opinion.
> > 
> > 
> > I'd change the parameter name for the pull secret to something more generic; it's not artifactory specific and we should not imply it is with the name of the parameter.
> > The build does not have to be artifactory specific. You can override the `FROM` directive in the Docker file by adding a `dockerStrategy` section to the build like this (from [bcgov/orgbook-configurations - backup-build.json](https://github.com/bcgov/orgbook-configurations/blob/master/openshift/templates/backup/backup-build.json#L52)):
> > ```
> >   strategy:
> >     type: Docker
> >     dockerStrategy:
> >       from:
> >         kind: DockerImage
> >         name: 'registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
> >       dockerfilePath: Dockerfile
> > ```
> > 
> > 
> > That way you can leave the `FROM nginx:stable` in the proxy's Dockerfile and inject the artifactory specific URI in the OCP build. Then we're not forcing our specific infrastructure configuration on others.
> 
> how do we inject the artifactory creds with this new configuration?

The configuration for build credentials (probably a better name than artifactory as Wade pointed out) would remain the same, you would also add the `from` clause to override what is in the Dockerfile.

@WadeBarnes I am not sure how we would make the arifactory/build creds optional: thoughts?

Additionally, the other components in the project (database, api service) have the artifactory prefix hard-coded in the build configurations as they don't use a Dockerfile. The only thing I can think of for these objects is to make the docker registry addess a parameter that is added via string interpolation as we do elsewhere (see suffix), in which case the description needs to explicitly state that it needs to end with a `/` in order for it to work.

2021-01-07 18:37 UTC, esune approved these changes
Looks good to me

2021-01-07 21:38 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +          "role": "${ROLE}"
@WadeBarnes since this policy is required once per environment, and each environment will potentially have different apps, should we remove the `app`, `app-group` and `role` labels (and related parameters), since they don't really apply?

2021-01-07 22:52 UTC, wadeking98 commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +          "role": "${ROLE}"
I agree, I just changed it.

2021-01-08 00:04 UTC, esune requested changes

2021-01-08 00:04 UTC, esune commented on openshift/templates/matomo-proxy/matomo-proxy-build.json
> +    },
This is now unused

2021-01-08 01:31 UTC, esune approved these changes

2021-01-09 14:24 UTC, WadeBarnes requested changes
See comments

2021-01-09 14:24 UTC, WadeBarnes commented on README.md
> +#####Running with Artifactory:
```suggestion
##### Running with Artifactory:
```

2021-01-09 14:24 UTC, WadeBarnes commented on README.md
> +oc create secret docker-registry artifactory-creds \
Same comments apply; https://github.com/BCDevOps/fathom-openshift/pull/7#discussion_r554245939

2021-01-09 14:24 UTC, WadeBarnes commented on README.md
> +#####Running with custom Docker registry:
```suggestion
##### Running with custom Docker registry:
```

2021-01-09 14:24 UTC, WadeBarnes commented on README.md
> +#####Deploy:
```suggestion
##### Deploy:
```

2021-01-09 14:24 UTC, WadeBarnes commented on openshift/templates/matomo-proxy/matomo-proxy-build.yaml
> +            name: ${DOCKER_REG}nginx:stable
I'd recommend parameterizing `nginx:stable`

2021-01-09 14:24 UTC, WadeBarnes commented on openshift/templates/matomo/matomo-deploy.yaml
> +
Remove extra whitespace

2021-01-11 21:49 UTC, esune commented on README.md
> +oc create secret docker-registry artifactory-creds \
Same comment from me as well: this should just be a link to the docs on developer.gov.bc.ca

2021-01-11 21:50 UTC, esune approved these changes
Other than the comment on the docs, changes look good to me.

2021-01-13 18:02 UTC, esune approved these changes

2021-01-13 18:02 UTC, merged