Extracted general NSPs to own configuration files, added backup flag to db deployment.
BCDevOps/matomo-openshift pull request #21
Opened 2021-02-16 23:20 UTC by esune

Clean-up and reorganized NSP templates, added backup label to be used with backup-container instances.

2021-02-20 12:51 UTC, WadeBarnes requested changes

2021-02-20 12:51 UTC, WadeBarnes commented on openshift/manage
> +      echoWarning "\nApplying required network security policies."
https://github.com/BCDevOps/openshift-developer-tools/pull/129, adds support for defining discrete NSP configurations for build and deployment environments.  NSP configuration are managed and processed just like regular build and deployment configurations which will eliminate the separate processing needed in the `manage` script.

2021-02-24 01:18 UTC, esune commented
@WadeBarnes take a look at the latest iteration/idea: probably not perfect, but I think it will work.

On `init` both `build` and `deploy` parameter files are processed and the environment variables are replaced with the default values. However, since we do not know in which target namespace the app will be deployed into, the deployment files are re-processed again before deploying in order to ensure the default value (in this case `latest`, which wouldn't really work anyway) is replaced with the appropriate environment name `dev/test/prod/tools` selected at deployment time.

I am not a huge fan of re-processing things, but given the use-case I think this is inevitable for this specific scenario.

2021-02-24 19:24 UTC, WadeBarnes approved these changes

2021-02-24 19:24 UTC, merged